# Generated by Django 5.1.5 on 2025-01-29 17:22

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('serial_num', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='Close', max_length=10)),
                ('settings', models.CharField(default='-', max_length=255)),
                ('admin', models.CharField(default='Off', max_length=10)),
                ('sync', models.CharField(default='False', max_length=5)),
                ('user', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('used', models.CharField(choices=[('C', 'Constant'), ('T', 'Temporary'), ('O', 'One use')], default='T', max_length=10)),
                ('time_start', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('selection', models.CharField(choices=[('-', '0'), ('+1h', '1 hour'), ('+1d', '1 day'), ('+1w', '1 week'), ('+2w', '2 week')], default='-', max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.devicemodel')),
            ],
        ),
    ]
